package vistas;

import controladores.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ProcesoUI extends javax.swing.JPanel {

    private Controlador controlador;

    /**
     * Creates new form ProcesoUI
     */
    public ProcesoUI() {
        initComponents();
        controlador = new Controlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonSiguiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonNuevoProceso = new javax.swing.JButton();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaTiempoArribo = new javax.swing.JLabel();
        campoTiempoArribo = new javax.swing.JTextField();
        etiquetaDuracionTotal = new javax.swing.JLabel();
        campoDuracionProceso = new javax.swing.JTextField();
        etiquetaMemoriaRequerida = new javax.swing.JLabel();
        campoMemoriaRequerida = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonEliminarProceso = new javax.swing.JButton();
        jsp = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(550, 300));
        setMinimumSize(new java.awt.Dimension(550, 300));
        setPreferredSize(new java.awt.Dimension(550, 300));
        setLayout(new java.awt.BorderLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Crear Tanda de Procesos");
        add(titulo, java.awt.BorderLayout.PAGE_START);

        botonSiguiente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonSiguiente.setText("Ingresar Datos del Simulador");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 387, Short.MAX_VALUE)
                .addComponent(botonSiguiente))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSiguiente))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        botonNuevoProceso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonNuevoProceso.setText("Nuevo Proceso");
        botonNuevoProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoProcesoActionPerformed(evt);
            }
        });

        etiquetaNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaNombre.setText("Nombre");
        etiquetaNombre.setEnabled(false);

        campoNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoNombre.setEnabled(false);

        etiquetaTiempoArribo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaTiempoArribo.setText("Tiempo de arribo [seg]");
        etiquetaTiempoArribo.setEnabled(false);

        campoTiempoArribo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoTiempoArribo.setEnabled(false);

        etiquetaDuracionTotal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaDuracionTotal.setText("Duración total [seg]");
        etiquetaDuracionTotal.setEnabled(false);

        campoDuracionProceso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoDuracionProceso.setEnabled(false);

        etiquetaMemoriaRequerida.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaMemoriaRequerida.setText("Memoria requerida [kb]");
        etiquetaMemoriaRequerida.setEnabled(false);

        campoMemoriaRequerida.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoMemoriaRequerida.setEnabled(false);

        botonAgregar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.setEnabled(false);
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setEnabled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaTiempoArribo)
                            .addComponent(etiquetaDuracionTotal)
                            .addComponent(etiquetaMemoriaRequerida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoMemoriaRequerida)
                            .addComponent(campoDuracionProceso)
                            .addComponent(campoTiempoArribo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(etiquetaNombre)
                                .addGap(18, 18, 18)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(botonAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonCancelar))))
                    .addComponent(botonNuevoProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevoProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTiempoArribo)
                    .addComponent(campoTiempoArribo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDuracionTotal)
                    .addComponent(campoDuracionProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMemoriaRequerida)
                    .addComponent(campoMemoriaRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonCancelar))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.LINE_END);

        botonEliminarProceso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonEliminarProceso.setText("Eliminar Proceso");
        botonEliminarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProcesoActionPerformed(evt);
            }
        });

        tablaProcesos.setModel(new ProcesoTableModel());
        jsp.setViewportView(tablaProcesos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarProceso)
                    .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(botonEliminarProceso)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoProcesoActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_botonNuevoProcesoActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        try {
            String nombre = campoNombre.getText();
            String tiempoArribo = campoTiempoArribo.getText();
            String duracion = campoDuracionProceso.getText();
            String memoriaRequerida = campoMemoriaRequerida.getText();
            controlador.registrarNuevoProceso(nombre, tiempoArribo, duracion, memoriaRequerida);
            deshabilitarCampos();
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null,
                    "Los datos ingresados no son numéricos.",
                    "Error Numérico",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException nullPointerException) {
            JOptionPane.showMessageDialog(null,
                    "Ingrese todos los datos correctamente.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        deshabilitarCampos();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEliminarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProcesoActionPerformed
        controlador.eliminarProceso(tablaProcesos.getSelectedRow());
    }//GEN-LAST:event_botonEliminarProcesoActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        controlador.iniciarVentanaSimulador();
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void habilitarCampos() {
        campoDuracionProceso.setText("");
        campoMemoriaRequerida.setText("");
        campoNombre.setText("");
        campoTiempoArribo.setText("");
        campoDuracionProceso.setEnabled(true);
        campoMemoriaRequerida.setEnabled(true);
        campoNombre.setEnabled(true);
        campoTiempoArribo.setEnabled(true);
        etiquetaDuracionTotal.setEnabled(true);
        etiquetaMemoriaRequerida.setEnabled(true);
        etiquetaNombre.setEnabled(true);
        etiquetaTiempoArribo.setEnabled(true);
        botonAgregar.setEnabled(true);
        botonCancelar.setEnabled(true);
    }

    private void deshabilitarCampos() {
        campoDuracionProceso.setText("");
        campoMemoriaRequerida.setText("");
        campoNombre.setText("");
        campoTiempoArribo.setText("");
        campoDuracionProceso.setEnabled(false);
        campoMemoriaRequerida.setEnabled(false);
        campoNombre.setEnabled(false);
        campoTiempoArribo.setEnabled(false);
        etiquetaDuracionTotal.setEnabled(false);
        etiquetaMemoriaRequerida.setEnabled(false);
        etiquetaNombre.setEnabled(false);
        etiquetaTiempoArribo.setEnabled(false);
        botonAgregar.setEnabled(false);
        botonCancelar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminarProceso;
    private javax.swing.JButton botonNuevoProceso;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField campoDuracionProceso;
    private javax.swing.JTextField campoMemoriaRequerida;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTiempoArribo;
    private javax.swing.JLabel etiquetaDuracionTotal;
    private javax.swing.JLabel etiquetaMemoriaRequerida;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTiempoArribo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tablaProcesos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
